backend:
  name: github
  repo: devilikex/devilikex.github.io
  branch: main


media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "updates_collection"
    label: "Updates"
    files:
      - file: "_data/updates.json"
        label: "Blog Updates"
        name: "blog_updates"
        fields:
          - label: "Blog Posts"
            name: "posts"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Publish Date", name: "date", widget: "datetime"}
              - {label: "Body", name: "body", widget: "markdown"}
